/**
 * Stubbed API — UI contract tests.
 *
 * All /api/* requests are intercepted with page.route() so this suite needs
 * no running API server, no OpenAI key, and no database.
 *
 * Auth: If .auth/user.json exists (generated by the live global-setup), the
 * Playwright config loads it as storageState and tests start pre-authenticated.
 * When the file is absent the beforeEach skips each test with a clear message
 * explaining how to produce the auth state — the suite itself always starts
 * successfully; only individual tests skip.
 *
 * Run (no secrets needed — just a running web app):
 *   PLAYWRIGHT_BASE_URL=https://<replit-dev-domain> \
 *     pnpm --filter @workspace/tests test:e2e
 */

import path from "path";
import fs from "fs";
import { test, expect } from "@playwright/test";

// Path to auth state (same derivation as playwright.config.ts)
const AUTH_STATE = path.join(__dirname, "..", ".auth", "user.json");

// ---------------------------------------------------------------------------
// Shared mock payloads
// ---------------------------------------------------------------------------

const MOCK_PROCESSING = {
  id: 42,
  category: "school",
  classOrCourse: "12th Science",
  boardOrUniversity: "CBSE",
  subject: "Physics",
  yearsAnalyzed: null,
  status: "processing",
  hasPdf: false,
  createdAt: new Date().toISOString(),
};

const MOCK_COMPLETED = {
  ...MOCK_PROCESSING,
  status: "completed",
  yearsAnalyzed: 1,
  hasPdf: true,
  aiResponse: {
    subject: "Physics",
    category: "school",
    years_analyzed: 1,
    overall_strategy_tip:
      "Mechanics accounts for ~40 % of marks — prioritise it first.",
    chapters: [
      {
        chapter_name: "Mechanics",
        priority: "High",
        marks_weightage: "25",
        frequency: 8,
        study_note: "Focus on Newton's laws and rotational motion.",
      },
      {
        chapter_name: "Thermodynamics",
        priority: "Medium",
        marks_weightage: "15",
        frequency: 5,
        study_note: "Understand the laws with worked examples.",
      },
      {
        chapter_name: "Optics",
        priority: "Low",
        marks_weightage: "10",
        frequency: 3,
        study_note: "Revision only — rarely tested in depth.",
      },
    ],
  },
};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Wire all /api/* page.route() stubs. */
async function wireApiStubs(page: import("@playwright/test").Page) {
  let pollCount = 0;

  await page.route("**/api/upload", (route) => {
    if (route.request().method() !== "POST") return route.continue();
    return route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify({ filePaths: ["/tmp/uploads/physics-2023.pdf"] }),
    });
  });

  await page.route("**/api/analyses", (route) => {
    if (route.request().method() !== "POST") return route.continue();
    return route.fulfill({
      status: 201,
      contentType: "application/json",
      body: JSON.stringify(MOCK_PROCESSING),
    });
  });

  await page.route("**/api/analyses/42", (route) => {
    if (route.request().url().includes("/download")) return route.continue();
    if (route.request().method() !== "GET") return route.continue();
    pollCount++;
    return route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify(pollCount <= 2 ? MOCK_PROCESSING : MOCK_COMPLETED),
    });
  });

  await page.route("**/api/analyses/42/download", (route) => {
    if (route.request().method() !== "GET") return route.continue();
    return route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify({ url: "/api/pdf/study-guide-42.pdf" }),
    });
  });

  await page.route("**/api/pdf/**", (route) =>
    route.fulfill({
      status: 200,
      contentType: "application/pdf",
      body: Buffer.from("%PDF-1.4 stub"),
    }),
  );
}

// ---------------------------------------------------------------------------
// Suite
// ---------------------------------------------------------------------------

test.describe("Stubbed API — UI contract", () => {
  test.beforeEach(() => {
    // Skip with a clear, actionable message when there is no auth state.
    // The suite itself starts successfully — only the individual test skips.
    test.skip(
      !fs.existsSync(AUTH_STATE),
      "No .auth/user.json found. Run the live suite first to generate auth state: " +
        "PLAYWRIGHT_BASE_URL=<url> pnpm --filter @workspace/tests test:e2e:live. " +
        "The stubbed suite itself launches successfully — only tests that require " +
        "an authenticated session are skipped when the auth state file is absent.",
    );
  });

  test(
    "fills form → uploads PDF (stub) → waits for analysis (stub) → sees chapters → downloads PDF (stub)",
    async ({ page }) => {
      await wireApiStubs(page);

      // --- Step 1: subject form ---
      await page.goto("/analyze");
      await expect(page.getByText("What are we studying?")).toBeVisible();

      await page.getByRole("button", { name: /School \/ Board/i }).click();
      await page.getByLabel(/Class/i).fill("12th Science");
      await page.getByLabel(/Board/i).fill("CBSE");
      await page.getByLabel(/Subject Name/i).fill("Physics");
      await page.getByRole("button", { name: /Next Step/i }).click();

      // --- Step 2: upload an inline PDF buffer (no file system needed) ---
      await expect(page.getByText(/Apna paper upload/i)).toBeVisible();
      await page.locator('input[type="file"]').setInputFiles({
        name: "physics-2023.pdf",
        mimeType: "application/pdf",
        buffer: Buffer.from(
          "%PDF-1.4\n1 0 obj<</Type/Catalog>>endobj\n%%EOF",
        ),
      });
      await expect(page.getByText("physics-2023.pdf")).toBeVisible();
      await page.getByRole("button", { name: /Analyze Papers/i }).click();

      // --- Step 3: processing indicator ---
      await expect(
        page.getByText(
          /padhe ja rahe|Patterns dhundhe|AI analysis|Study guide ban/i,
        ),
      ).toBeVisible({ timeout: 10_000 });

      // --- Wait for redirect — stubs resolve after 3 polls × ~2 s ≈ 6 s ---
      await page.waitForURL("**/analyses/42", { timeout: 30_000 });

      // --- Step 4: chapter list ---
      await expect(page.getByText("Chapter Priority List")).toBeVisible({
        timeout: 10_000,
      });
      await expect(page.getByText("Mechanics")).toBeVisible();
      await expect(page.getByText("Thermodynamics")).toBeVisible();
      await expect(page.getByText("Optics")).toBeVisible();
      await expect(page.getByText(/High Priority/i).first()).toBeVisible();

      // --- Step 5: PDF download ---
      const downloadBtn = page.getByRole("button", {
        name: /Download Study Guide PDF/i,
      });
      await expect(downloadBtn).toBeEnabled();

      // Capture the URL passed to window.open (fires asynchronously)
      await page.evaluate(() => {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        (window as any).__capturedPdfUrl = null;
        const orig = window.open.bind(window);
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        window.open = function (url?: string | URL, ...rest: any[]) {
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          (window as any).__capturedPdfUrl = String(url ?? "");
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          return (orig as any)(url, ...rest);
        };
      });

      await downloadBtn.click();

      await page.waitForFunction(
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        () => (window as any).__capturedPdfUrl !== null,
        { timeout: 10_000 },
      );

      const openedUrl: string = await page.evaluate(
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        () => (window as any).__capturedPdfUrl,
      );
      expect(openedUrl).toMatch(/\/api\/pdf\//);
    },
  );
});
