/**
 * Full-stack live tests — real API, real OpenAI, real PDF.
 *
 * No page.route() stubs. The browser makes genuine HTTP requests to the
 * running API server. Auth comes from .auth/user.json saved by global-setup.ts
 * (via playwright.live.config.ts storageState) — no sign-in interaction needed
 * inside test bodies.
 *
 * Requires (as Replit secrets):
 *   CLERK_SECRET_KEY  — so global-setup.ts can create the test user and
 *                       save the auth storage state
 *   DATABASE_URL      — auto-provided in the Replit workspace
 *   OPENAI_API_KEY    — auto-provided in the Replit workspace
 *
 * Run via:
 *   PLAYWRIGHT_BASE_URL=https://<replit-dev-domain> \
 *     pnpm --filter @workspace/tests test:e2e:live
 */

import { test, expect } from "@playwright/test";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Retrieve the fixture PDF path set by global-setup. Throws on missing. */
function requireFixturePdf(): string {
  const p = process.env.TEST_FIXTURE_PDF_PATH;
  if (!p) {
    throw new Error(
      "TEST_FIXTURE_PDF_PATH not set — global-setup did not generate the PDF " +
        "fixture. Check global-setup output for errors.",
    );
  }
  return p;
}

// ---------------------------------------------------------------------------
// Suite
// ---------------------------------------------------------------------------

test.describe("Full-stack — real API (no route stubs)", () => {
  // Auth is pre-loaded via storageState in playwright.live.config.ts —
  // no sign-in step needed here.

  test(
    "sign in → upload real PDF → wait for AI analysis → see chapters → download PDF",
    async ({ page }) => {
      // Allow 3 minutes for this test: real OpenAI analysis takes 30–90 s
      test.setTimeout(3 * 60 * 1000);

      // ------------------------------------------------------------------ 1
      // Navigate to Analyze — should land directly (pre-authenticated)
      await page.goto("/analyze");
      await expect(page.getByText("What are we studying?")).toBeVisible();

      // ------------------------------------------------------------------ 2
      // Step 1 — fill subject form
      await page.getByRole("button", { name: /School \/ Board/i }).click();
      await page.getByLabel(/Class/i).fill("12th Science");
      await page.getByLabel(/Board/i).fill("CBSE");
      await page.getByLabel(/Subject Name/i).fill("Physics");
      await page.getByRole("button", { name: /Next Step/i }).click();

      // ------------------------------------------------------------------ 3
      // Step 2 — upload the real PDF fixture generated by global-setup
      await expect(page.getByText(/Apna paper upload/i)).toBeVisible();
      await page
        .locator('input[type="file"]')
        .setInputFiles(requireFixturePdf());
      await expect(page.getByText("sample-question-paper.pdf")).toBeVisible();
      await page.getByRole("button", { name: /Analyze Papers/i }).click();

      // ------------------------------------------------------------------ 4
      // Processing indicator must appear
      await expect(
        page.getByText(
          /padhe ja rahe|Patterns dhundhe|AI analysis|Study guide ban/i,
        ),
      ).toBeVisible({ timeout: 15_000 });

      // ------------------------------------------------------------------ 5
      // Wait for real AI to finish — app redirects to /analyses/:id
      await page.waitForURL("**/analyses/**", { timeout: 180_000 });

      // ------------------------------------------------------------------ 6
      // Verify chapter list rendered with real AI results
      await expect(page.getByText("Chapter Priority List")).toBeVisible({
        timeout: 15_000,
      });

      // At least one chapter card with a Priority badge must exist
      const chapterCards = page
        .locator(".card, [class*='card']")
        .filter({ hasText: /Priority/i });
      await expect(chapterCards.first()).toBeVisible();

      // Subject heading must appear in the result
      await expect(page.getByText("Physics")).toBeVisible();

      // ------------------------------------------------------------------ 7
      // Click "Download Study Guide PDF" — verify the PDF URL fires
      const downloadBtn = page.getByRole("button", {
        name: /Download Study Guide PDF/i,
      });
      await expect(downloadBtn).toBeVisible();
      await expect(downloadBtn).toBeEnabled();

      // Intercept window.open so we can assert the URL without navigating away
      await page.evaluate(() => {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        (window as any).__capturedPdfUrl = null;
        const orig = window.open.bind(window);
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        window.open = function (url?: string | URL, ...rest: any[]) {
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          (window as any).__capturedPdfUrl = String(url ?? "");
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          return (orig as any)(url, ...rest);
        };
      });

      await downloadBtn.click();

      await page.waitForFunction(
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        () => (window as any).__capturedPdfUrl !== null,
        { timeout: 15_000 },
      );

      const openedUrl: string = await page.evaluate(
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        () => (window as any).__capturedPdfUrl,
      );

      // URL must point at the generated PDF served by the API server
      expect(openedUrl).toMatch(/\/api\/pdf\//);
    },
  );
});
