/**
 * Playwright config — STUBBED suite (page.route stubs, no secrets required).
 *
 * All /api/* calls are intercepted with page.route(). This suite verifies
 * the frontend flow (form → upload → polling → chapter list → PDF download)
 * without touching the real API server, database, or AI.
 *
 * Auth: If .auth/user.json exists (generated by the live global-setup),
 * tests start pre-authenticated. If it does not exist, each test is skipped
 * with a clear message — the suite itself never fails at setup when
 * credentials are absent.
 *
 * Run (no secrets needed — just a running web app):
 *   PLAYWRIGHT_BASE_URL=https://<replit-dev-domain> \
 *     pnpm --filter @workspace/tests test:e2e
 *
 * Run with auth (after running the live suite or global-setup first):
 *   # 1. Generate auth state (once):
 *   PLAYWRIGHT_BASE_URL=... pnpm --filter @workspace/tests test:e2e:live
 *   # 2. Stubbed suite now has auth state available
 *   PLAYWRIGHT_BASE_URL=... pnpm --filter @workspace/tests test:e2e
 */
import path from "path";
import fs from "fs";
import { defineConfig, devices } from "@playwright/test";

const BASE_URL = process.env.PLAYWRIGHT_BASE_URL ?? "http://localhost:5173";
const AUTH_STATE = path.join(__dirname, ".auth", "user.json");

export default defineConfig({
  testDir: "./e2e",
  testMatch: ["**/flow.stubbed.spec.ts"],
  fullyParallel: false,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 1 : 0,
  reporter: "html",
  timeout: 60_000,

  use: {
    baseURL: BASE_URL,
    // Use saved auth state when it exists (from a prior live-suite run)
    storageState: fs.existsSync(AUTH_STATE) ? AUTH_STATE : undefined,
    trace: "on-first-retry",
    screenshot: "only-on-failure",
    actionTimeout: 30_000,
    navigationTimeout: 30_000,
  },

  // NO globalSetup — this suite requires zero external secrets to execute.

  projects: [
    {
      name: "chromium",
      use: { ...devices["Desktop Chrome"] },
    },
  ],
});
